### ISSUE TITLE
Viruses in this software

### ISSUE THREAD

**Issue by VPDPIN** [theowlhoothoot/MegaSync#1]
https://www.virustotal.com/gui/file/9defaaf7435832e998bd696f65b8fd95c9c3cdfaf6361e793a3579e98796ce02

Antiy-AVL

Trojan/Generic.ASMalwS.3507346
Cynet

Malicious (score: 100)
Cyren

W64/Tedy.B.gen!Eldorado
McAfee-GW-Edition

BehavesLike.Win64.Generic.tc
SecureAge APEX

Malicious
Yandex

Riskware.Themida!1BfR0pvsJX4
Zillya

Trojan.Agent.Script.1666853

**Comment by theowlhoothoot** [comment]
This is flagging well known module and should be a false positive. This could be a result of the pyinstaller to exe ddl creation process and you are more than welcome to self compile using your pyinstaller with the native python packages. All parts of the script are open source and available for review.

https://pypi.org/project/altgraph/
https://github.com/ronaldoussoren/altgraph

![image](https://user-images.githubusercontent.com/76261646/154849094-c40ddc39-245b-4a16-8358-1a4b26de0020.png)

**Comment by theowlhoothoot** [comment]
This also appears to be a known issue with pyinstaller sometimes. I will go ahead and close with and recommend to self compile.

https://stackoverflow.com/questions/43777106/program-made-with-pyinstaller-now-seen-as-a-trojan-horse-by-avg
